# Generated by Django 4.2.30 on 2026-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cost_index',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Daily cost estimate in INR', max_digits=8),
        ),
    ]
